Handled Deletion of User and Improved Logout transition
software-students-fall2021/project-setup-dyor pull request #198
Opened 2021-12-03 23:07 UTC by aqhra050

2021-12-04 00:09 UTC, aqhra050 commented
![image](https://user-images.githubusercontent.com/18217147/144688246-881ef12e-d944-4145-8a4c-f18752ee28ac.png)

2021-12-05 10:22 UTC, Des-cloud requested changes
Test cases not passing.

2021-12-05 19:04 UTC, sashanksilwal approved these changes

2021-12-05 21:14 UTC, sashanksilwal approved these changes

2021-12-05 21:46 UTC, Des-cloud approved these changes
Great

2021-12-05 21:47 UTC, merged